### ISSUE TITLE
Does this library work with WebSockets?

### ISSUE THREAD

**Issue by sashaafm** [gausby/gen_mqtt#21]
Hello @gausby, does this library work with MQTT over WebSockets? I'm having some trouble connecting as the `on_connect` callback never seems to be triggered.

Thanks!

**Comment by gausby** [comment]
The supported transports are `gen_tcp` and `sll`, so I am afraid this can't help you. This project uses the `gen_emqtt` module that was developed by Erlio, the makers of VerneMQ, and I think they use it for building the bridge mode between two MQTT brokers, and for testing VerneMQ itself. Websockets has not been a priority.

I am building a new MQTT client for Elixir, but I am afraid it takes a bit of time because it is a sparetime project, but perhaps I should look into websockets for that.

**Comment by gausby** [comment]
The new client can be found here: http://github.com/gausby/tortoise/

I need to look into alternative connection types than the currently implemented tcp-option. Websockets would definitely be interesting. Please look into Tortoise and see if it fits your needs design wise, and if it doesn't please tell me; issues on Tortoise will work, or send me emails on martin at gausby dot dk. Thanks :)

**Comment by sashaafm** [comment]
Wow, you did deliver 👏 great @gausby!!! Thanks 😄

**Comment by gausby** [comment]
Sorry it took so long time. I was way too ambitious with my first implementation, even had plans for a process registry with MQTT semantics, so one could register processes on MQTT topics…that sounds like a fine project, but Tortoise scaled the plans way down, and I think it fits more what is actually needed, because I don't think it is common to change topics that often :)
